apiVersion: apps/v1
kind: Deployment
metadata:
  name: fritzbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fritzbox-exporter
  template:
    metadata:
      labels:
        app: fritzbox-exporter
    spec:
      containers:
        - args: []
          image: tkeber/fritzbox_exporter:0.1.0
          imagePullPolicy: IfNotPresent
          name: fritzbox-exporter
      tolerations: []
