apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9042"
    prometheus.io/scrape: "true"
  name: fritzbox-exporter
spec:
  ports:
  - name: http
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: fritzbox-exporter
  type: ClusterIP
